Finished Object-manipulation-1
DreSean-Sutton/c1021-code-solutions pull request #59
Opened 2021-11-03 04:25 UTC by DreSean-Sutton

![image](https://user-images.githubusercontent.com/90172283/140009903-4e31881b-385a-43c4-a65b-3ae07eebfa18.png)

2021-11-03 22:32 UTC, codingcodymiller requested changes

2021-11-03 22:32 UTC, codingcodymiller commented on object-manipulation-1/src/set-value.js
> +  }
This is unnecessary

2021-11-03 22:32 UTC, codingcodymiller commented on object-manipulation-1/src/set-value.js
> +  var newObj = object[key] = value;
There is no need for this variable, you just need to do the work of assigning the value to the key. There is also no return for this function.
![Screen Shot 2021-11-03 at 3 31 59 PM](https://user-images.githubusercontent.com/32880187/140209234-851c9af8-9c8a-4294-8a7b-9d27fcec4b0c.png)

2021-11-04 16:11 UTC, DreSean-Sutton commented
![image](https://user-images.githubusercontent.com/90172283/140376643-8a7ca407-401f-44d3-b710-76c2351e634e.png)

2021-11-16 17:25 UTC, codingcodymiller approved these changes

2021-11-18 00:02 UTC, merged